name: Scrape and commit

on:
  workflow_dispatch:
  schedule:
    # once a day at  5:15, 11:15, 17:15 on JST
    - cron: '15 20,2,8 * * *'

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: setup
      run: |- 
        sudo apt-get install -y --no-install-recommends libsqlite3-mod-spatialite
        pip install sqlite-utils
    - name: scrape
      run: bash scripts/scrape.sh
    - name: Commit and push
      run: |-
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add -A

        # check rows affected
        rows=$(awk '{sum += $1} END {print sum}' data/tmp/rows_affected.txt)

        # if no rows affected, exclude data/jma.db from commit
        if [ $rows -eq 0 ]; then
          echo "No rows affected. exclude data/jma.db from commit"
          git reset data/jma.db
        fi

        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
